### ISSUE TITLE
failed ListActivities call (page 601, per page 25)

### ISSUE THREAD

**Issue by cjonhammar** [vangent/stravacli#10]
Getting this, when trying to fetch this years activities by running:
~/go/bin/stravacli download --access_token=xxx --out=orig.csv --debug --after=2019-01-01 --max=599 --before 2019-12-20

25 activities so far, fetching next 25...
50 activities so far, fetching next 25...
75 activities so far, fetching next 25...
snip
475 activities so far, fetching next 25...
500 activities so far, fetching next 25...
519 activities so far, fetching next 25...
519 activities so far, fetching next 25...
519 activities so far, fetching next 25...
519 activities so far, fetching next 25...
519 activities so far, fetching next 25...
snip
507 activities so far, fetching next 25...
507 activities so far, fetching next 25...
507 activities so far, fetching next 25...
failed ListActivities call (page 601, per page 25)

If I do only before like this:
~/go/bin/stravacli download --access_token=xxxx --out=orig.csv --debug --before=2019-12-20 --max=599
Then it works fine

**Comment by vangent** [comment]
Thanks for the report! Think I fixed this via https://github.com/vangent/stravacli/commit/fa45302f80a6b4289ce3ec020c141c12ebcbeed8.

**Comment by cjonhammar** [comment]
Thanks, works!
